### ISSUE TITLE
Reach Out

### ISSUE THREAD

**Issue by ajain-1** [fragileqt/LocationBasedARCore#1]
Hey @fragileqt . This isn't an issue about this repo. I was using your `vue-hero` npm package to get hero animations in vue using vue router. When using it I keep getting a lot of errors about hero deep and styles. Below is what I am trying to do. If you could help me it would be amazing. 

Screen 1
```
      <Hero :tag="0" key="img1" :styles="['borderRadius', 'fontSize']" >
        <v-img
          hero-deep="true"
          :hero-index="-1"
          :ref="0"
          :src="info.servicePicture"
        ></v-img>
      </Hero>
```
Screen 2
```
      <Hero :tag="0" key="img2" :styles="['borderRadius', 'fontSize']" >
        <v-img
          hero-deep="true"
          :hero-index="-1"
          :ref="0"
          :src="info.servicePicture"
        ></v-img>
      </Hero>
```
Can you please help me? I am using vue router to navigate between the two pages. I don't really understand the docs on the npm package you have and how to use hero-deep, ref, index, tag, key, styles, etc with vue router. Thank you so much.

**Comment by fragileqt** [comment]
Hello @ShadeAJ1, 

can you please share a log of errors you get? Also I couldn't figure out how to read styles applied from external css, that's why you have to use inline css in yours v-img element to get borderRadius animation working. 

Also feel free to hit me up on any messaging service (Whatsapp / Messenger / Hangouts), so we don't  spam this repo. My email is: zateklukas@gmail.com

**Comment by ajain-1** [comment]
Thank you for responding so quickly! I emailed you the errors I got.

**Comment by ShadeAJ1** [comment]
Hi Lukas,

First of all, thank you for the quick reply. I get the below errors.
[image: Screen Shot 2020-04-14 at 3.57.03 PM.png]
[image: Screen Shot 2020-04-14 at 3.56.48 PM.png]
Below is my code for both screen 1 and screen 2
[image: Screen Shot 2020-04-14 at 4.00.15 PM.png]
[image: Screen Shot 2020-04-14 at 4.00.01 PM.png]
What am I doing wrong? Which fields are required for the transition? Screen
1 and 2 are both components by the way. Please let me know and I really
appreciate your help. Thank you so much.

Thanks,

Aryan Jain
